version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=menu-creator-db
    networks:
      - menucreator-network
    restart: always
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://postgres:password@postgres:5432/menu-creator-db?sslmode=disable
    depends_on:
      - postgres
    # using entrypoint overrides the command in dockerfile, need to explicitly run command here
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]
    networks:
      - menucreator-network
    restart: always

networks:
  menucreator-network:
    driver: bridge