ALTER TABLE IF EXISTS "MenuItem" 
ALTER COLUMN "status" TYPE VARCHAR (1);

ALTER TABLE IF EXISTS "Menu" 
ALTER COLUMN "status" TYPE VARCHAR (1);

ALTER TABLE IF EXISTS "Ingredient" 
ALTER COLUMN "status" TYPE VARCHAR (1);

ALTER TABLE IF EXISTS "MenuItem_Ingredient" 
ALTER COLUMN "status" TYPE VARCHAR (1);

ALTER TABLE IF EXISTS "Menu_MenuItem" 
ALTER COLUMN "status" TYPE VARCHAR (1);