// Code generated by sqlc. DO NOT EDIT.
// source: menuItem.sql

package db

import (
	"context"
)

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO "MenuItem" (
  name, description, price
) VALUES (
  $1, $2, $3
)
RETURNING id, name, description, price, created_at
`

type CreateMenuItemParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       string `json:"price"`
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRowContext(ctx, createMenuItem, arg.Name, arg.Description, arg.Price)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}
