// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error)
}

var _ Querier = (*Queries)(nil)
